name: Aerospike Rust Client Tests

on:
  push:
    branches:
      - master
      - gh-actions
  pull_request:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  AEROSPIKE_HOSTS: 127.0.0.1:3000

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust ${{ matrix.rust }} toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - run: rustc --version
    - name: Set up Aerospike Database
      uses: reugn/github-action-aerospike@v1
      with:
        server-version: 5.5.0.2
# Start tokio CI
    - name: Clear cache before building with tokio
      run: rm -rf target/debug/deps/* # Clean everything before starting at all
    - name: Build with tokio
      run: cargo build --verbose --features rt-tokio
    - name: Run tests with tokio
      run: cargo test --verbose --features rt-tokio
# Start async-std CI
    - name: Clear cache before building with async-std
      run: rm -rf target/debug/deps/* # Clear everything because leftovers of the tokio build caused problems
    - name: Build with async-std
      run: cargo build --verbose --features rt-async-std
    - name: Run tests with async-std
      run: cargo test --verbose --features rt-async-std
# Start docs CI
    - name: Clear cache before building tokio again as clean doc test
      run: rm -rf target/debug/deps/* # Clear everything because duplicate libraries from the previous builds caused problems
    - name: Build with tokio
      run: cargo build --verbose --features rt-tokio # Use tokio for Doc tests since it makes no difference what runtime is selected
    - name: Build docs with async-std
      run: rustdoc -L target/debug/deps/ --test README.md # Only tests the docs in the Readme file
# Serialization steps are removed because serialization is now a default feature
