name: Aerospike Rust Client Tests

on:
  push:
    branches:
      - master
      - gh-actions
  pull_request:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  AEROSPIKE_HOSTS: 127.0.0.1:3000

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust ${{ matrix.rust }} toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - run: rustc --version
    - name: Set up Aerospike Database
      uses: reugn/github-action-aerospike@v1
    - name: Clear cache
      run: rm -rf target/debug/deps/*aerospike*
    - name: Build with tokio
      run: cargo build --verbose --features rt-tokio
    - name: Run tests with tokio
      run: cargo test --verbose --features rt-tokio
    - name: Build docs with tokio
      run: rustdoc -L target/debug/deps/ --test README.md
    - name: Clear cache
      run: rm -rf target/debug/deps/*aerospike*
    - name: Build with async-std
      run: cargo build --verbose --features rt-async-std
    - name: Run tests with async-std
      run: cargo test --verbose --features rt-async-std
    - name: Build docs with async-std
      run: rustdoc -L target/debug/deps/ --test README.md
# Serialization steps are removed because serialization is now a default feature
